version: "3.8"

services:
  products-service:
    container_name: products-service
    build: 
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - ENV=prod
    depends_on:
      - products-db

  products-db:
    container_name: products-db
    build: ./products-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - products:/var/lib/mongo

  users-service:
    container_name: users-service
    build: ./users-service
    ports:
      - 3000:3000
    environment:
      - ENV=prod
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: ./users-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - users:/var/lib/mysql

  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    depends_on:
      - users-service
      - products-service

 
volumes: # cannot use same name as any service
  products:
  users: